### ISSUE TITLE
Jinja ipaddr filter

### ISSUE THREAD

**Issue by ioc32** [ioc32/openhrc#11]
http://docs.ansible.com/playbooks_filters_ipaddr.html

It looks like our templates could extract the IP and nework addresses, as well as their prefixlens or netmasks, directly from variables.

Since our templates would no longer depend on the network-related ansible facts, should we consolidate both stages in one single playbook?

Requires ansible >1.9.1.
5.7 -release ships 1.8.4, but we could install the latest ansible stable version in it's own virtualenv.

[1] http://docs.ansible.com/pip_module.html

**Comment by saghul** [comment]
Sounds like an improvement!

**Comment by ioc32** [comment]
Alright I'll try and put something together in a separate feature branch.

On Mon, May 11, 2015 at 8:07 AM, Saúl Ibarra Corretgé <
notifications@github.com> wrote:

> Sounds like an improvement!
> On May 10, 2015 7:19 PM, "Malibu Carl" notifications@github.com wrote:
> 
> > http://docs.ansible.com/playbooks_filters_ipaddr.html
> > 
> > It looks like our templates could extract the IP and nework addresses, as
> > well as their prefixlens or netmasks, directly from variables.
> > 
> > Since our templates would no longer depend on the network-related ansible
> > facts, should we consolidate both stages in one single playbook?
> > 
> > Requires ansible >1.9.1.
> > 5.7 -release ships 1.8.4, but we could install the latest ansible stable
> > version in it's own virtualenv.
> > 
> > [1] http://docs.ansible.com/pip_module.html
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ioc32/openhrc/issues/11.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ioc32/openhrc/issues/11#issuecomment-100782151.

## 

"If you want to go fast, go alone. If you want to go far, go together."

**Comment by saghul** [comment]
Pssst, can we do this now, since 6.0 / 6.1 have a newer ansible?

**Comment by ioc32** [comment]
:rocket:
