### ISSUE TITLE
Moving 'install base packages' task to stage2

### ISSUE THREAD

**Issue by ioc32** [ioc32/openhrc#5]
Currently we handle the installation of packages in stage1.

To my mind, it makes more sense to move it to stage2. This way, stage1 would only be run once, while the rest of the system configuration can be perfomed idempotently with stage2.

I'd also like to rename the task as 'install packages' and the var as 'pkgs', since there's no distinction between 'base' and 'user' packages (for now).

For the record, I came up with this when installing mtr, which I am planning to add to the default list of OpenHRC packages ;-)

**Comment by saghul** [comment]
Sounds good! Actually I was thinking about shrinking the packages list to
the minimum, to make it (a tad) less opinionated ;-)

**Comment by ioc32** [comment]
Oh, in that case, I don't mind splitting the base and user packages today.

Let's use base_pkgs in stage1 and user_pkgs in stage2.

**Comment by ioc32** [comment]
If you are happy with my last commit, close the issue. Otherwise, amend and close :-)

**Comment by saghul** [comment]
Looking good!
